---
title: "Evaluation of Statistical Hypotheses"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r results = 'asis'}
cat("### ", study$name, "Postregistration", sep = " ")
```

```{r results = 'asis'}
for (author in study$authors) {
  name <- paste(author$name, collapse = ", ")
  if (author$orcid != "") {
    cat("* [", name, "](http://orcid.org/", author$orcid, ")\n", sep = "")
  } else {
    cat("* ", name, "\n", sep = "")
  }
  cat("    - roles: ", paste(author$roles, collapse = ", "), "\n")
  
  # any other attributes
  author$name <- NULL
  author$orcid <- NULL
  author$roles <- NULL
  for (attr in names(author)) {
    cat("    - ", attr, ": ", author[[attr]], "\n", sep = "")
  }
}
```

```{r results = 'asis'}
info_names <- names(study$info)

for (name in info_names) {
  val <- study$info[[name]]
  if (length(val) > 1) {
    val <- paste("*", paste(val, collapse = "\n* "))
  }
  cat("#### ", stringr::str_to_title(name), "\n\n", val, "\n\n\n", sep = "")
}
```


```{r results='asis'}
output_results(study)
```

```{r results='asis'}
output_analyses(study)
```
