---
title: "Registration Demo"
author: "Lisa DeBruine & Daniel Lakens"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(reg)
```

### Functional Setup

```{r}
# set up empty study object
mystudy <- study("IAT Demo")

# add hypothesis 1
mystudy <- add_hypothesis(
  study = mystudy,
  description = "Mean RT will be significantly slower in the incongruent condition compared to the congruent condition.",
  evaluation = "&",
  id = "H1"
)

# add analysis 1
mystudy <- add_analysis(
  study = mystudy,
  func = "t.test",
  params = list(
    x = ".data$incongruent",
    y = ".data$congruent",
    alternative = "two.sided",
    paired = TRUE,
    var.equal = FALSE,
    conf.level = 0.95
  ),
  id = "H1_ttest"
)

# add criterion 1 to hypothesis 1
mystudy <- add_criterion(
  study = mystudy,
  result = "p.value",
  operator = "<",
  comparator = .05,
  hypothesis_id = "H1",
  analysis_id = "H1_ttest"
)

# add criterion 2 to hypothesis 1
mystudy <- add_criterion(
  study = mystudy,
  result = "estimate",
  operator = ">",
  comparator = 0,
  hypothesis_id = "H1",
  analysis_id = "H1_ttest"
)

# add hypothesis 2
mystudy <- add_hypothesis(
  study = mystudy,
  description = "Reaction times for congruent and incongruent trials will be signifiantly and positively correlated.",
  evaluation = "&",
  id = "H2"
)

# add analysis 2
mystudy <- add_analysis(
  study = mystudy,
  func = "cor.test",
  params = list(
    x = ".data$congruent",
    y = ".data$incongruent",
    alternative = "two.sided",
    method = "pearson",
    conf.level = 0.95
  ),
  id = "H2_cor"
)

# add criterion 2 to hypothesis 2
mystudy <- add_criterion(
  study = mystudy,
  result = "p.value",
  operator = "<",
  comparator = 0.05,
  hypothesis_id = "H2",
  analysis_id = "H2_cor"
)

# add criterion 2 to hypothesis 2
mystudy <- add_criterion(
  study = mystudy,
  result = "estimate",
  operator = ">",
  comparator = 0,
  hypothesis_id = "H2",
  analysis_id = "H2_cor"
)
```

```{r, eval = FALSE}
# generate pre-registration report
study_report(mystudy, template="prereg", filename = "pre")
```

```{r, results='asis', echo = FALSE}
# output section of the report
mystudy %>%
  output_hypotheses() %>%
  output_analyses()
```

```{r}
# add data
n_sub <- 50
dat <- faux::rnorm_multi(n_sub, 2, .5, c(500, 750), 250,
                         c("congruent", "incongruent"))
dat$sub_id = 1:n_sub
mystudy <- add_data(mystudy, dat)

# run analyses
mystudy <- study_analyse(mystudy)
```

```{r eval = FALSE}
# generate post-registration report
study_report(mystudy, template="postreg")

```

```{r, results='asis', echo = FALSE}
# output section of the report
mystudy %>%
  output_results()
```


### Object-oriented setup

```{r}

mystudy <- study("IAT Demo")  %>%
  add_hypothesis(
    description = "Mean RT will be significantly slower in the incongruent condition compared to the congruent condition.",
    evaluation = "&", id = "H1") %>%
  add_analysis(
    func = "t.test",
    params = list(
      x = ".data$incongruent",
      y = ".data$congruent",
      alternative = "two.sided",
      paired = TRUE,
      var.equal = FALSE,
      conf.level = 0.95
    ),
    id = "H1_ttest"
  ) %>%
  add_criterion(
    result = "p.value",
    operator = "<",
    comparator = .05,
    hypothesis_id = "H1",
    analysis_id = "H1_ttest"
  ) %>%
  add_criterion(
    result = "estimate",
    operator = ">",
    comparator = 0,
    hypothesis_id = "H1",
    analysis_id = "H1_ttest"
  ) %>%
  add_hypothesis(
    description = "Reaction times for congruent and incongruent trials will be signifiantly and positively correlated.",
    evaluation = "&", id = "H2"
  ) %>%
  add_analysis(
    func = "cor.test",
    params = list(
      x = ".data$congruent",
      y = ".data$incongruent",
      alternative = "two.sided",
      method = "pearson",
      conf.level = 0.95
    ),
    id = "H2_cor"
  ) %>%
  add_criterion(
    result = "p.value",
    operator = "<",
    comparator = 0.05,
    hypothesis_id = "H2",
    analysis_id = "H2_cor"
  ) %>%
  add_criterion(
    result = "estimate",
    operator = ">",
    comparator = 0,
    hypothesis_id = "H2",
    analysis_id = "H2_cor"
  ) %>%
  add_data(dat) %>%
  study_analyse()
```

```{r, eval = FALSE}
mystudy %>%
  study_report(template="prereg", filename = "pre")
  study_report(template="postreg", filename = "post")
```

