test_that("multiplication works", {
  expect_equal(if_nowt(NULL), "")
  expect_equal(if_nowt(NA), "")
  expect_equal(if_nowt("   "), "")
  expect_equal(if_nowt(c(1, 2, NA), replace = 0), c(1, 2, 0))
  expect_equal(if_nowt(list(NULL, NA, " ")), list("", "", ""))
  expect_equal(if_nowt(list(NULL, NA, " "), test_for = "null"), list("", NA, " "))
  expect_equal(if_nowt(list(NULL, NA, " "), test_for = "na"), list(NULL, "", " "))
  expect_equal(if_nowt(list(NULL, NA, " "), test_for = "trim"), list(NULL, NA, ""))
})
