test_that("is_nowt", {
  x <- list(NA, NULL, "", " ", c(), list())
  expect_equal(is_nowt(NULL), TRUE)
  expect_equal(is_nowt(NA), TRUE)
  expect_equal(is_nowt("   "), TRUE)
  expect_equal(is_nowt(list()), TRUE)
  expect_equal(is_nowt(0), FALSE)
  expect_equal(is_nowt(1.3), FALSE)
  expect_equal(is_nowt("A"), FALSE)
  expect_equal(is_nowt(TRUE), FALSE)
  expect_equal(is_nowt(FALSE), FALSE)
  expect_equal(is_nowt(1:3), c(F, F, F))
  expect_equal(is_nowt(function(){}), FALSE)

  x <- list(NULL, NA, " ", list())
  expect_equal(is_nowt(x), list(T, T, T, T))
  expect_equal(is_nowt(x, test_for = "null"), list(T, F, F, F))
  expect_equal(is_nowt(x, test_for = "na"), list(F, T, F, F))
  expect_equal(is_nowt(x, test_for = "trim"), list(F, F, T, F))
  expect_equal(is_nowt(x, test_for = "empty"), list(F, F, F, T))
})

test_that("if_nowt", {
  expect_equal(if_nowt(NULL), "")
  expect_equal(if_nowt(NA), "")
  expect_equal(if_nowt("   "), "")
  expect_equal(if_nowt(list()), "")
  expect_equal(if_nowt(c(1, 2, NA), replace = 0), c(1, 2, 0))

  x <- list(NULL, NA, " ", list())
  expect_equal(if_nowt(x), list("", "", "", ""))
  expect_equal(if_nowt(x, test_for = "null"), list("", NA, " ", list()))
  expect_equal(if_nowt(x, test_for = "na"), list(NULL, "", " ", list()))
  expect_equal(if_nowt(x, test_for = "trim"), list(NULL, NA, "", list()))
  expect_equal(if_nowt(x, test_for = "empty"), list(NULL, NA, " ", ""))
})
