<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Export Study • scienceverse</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Export Study">
<meta property="og:description" content="scienceverse">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-160147578-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160147578-1');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">scienceverse</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9011</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/scienceverse/scienceverse/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="export_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Export Study</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/scienceverse/scienceverse/blob/master/vignettes/export.Rmd"><code>vignettes/export.Rmd</code></a></small>
      <div class="hidden name"><code>export.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">scienceverse</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt; ************</span>
<span class="co">#&gt; Welcome to scienceverse For support and examples visit:</span>
<span class="co">#&gt; http://scienceverse.github.io/</span>
<span class="co">#&gt; - Get and set global package options with: scienceverse_options()</span>
<span class="co">#&gt; ************</span></pre></body></html></div>
<p>Once you’ve created a scienceverse study, you can set up files from the meta-study file. Here’s a simple example testing group differences and simulating the data for the groups.</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="no">s</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/study.html">study</a></span>(<span class="st">"Demo"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_sim_data.html">add_sim_data</a></span>(<span class="st">"dat"</span>,
               <span class="kw">within</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">time</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"morning"</span>, <span class="st">"night"</span>)),
               <span class="kw">between</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">group</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"A"</span>, <span class="st">"B"</span>)),
               <span class="kw">mu</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">A</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">105</span>, <span class="fl">100</span>),
                         <span class="kw">B</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">105</span>, <span class="fl">100</span>)),
               <span class="kw">n</span> <span class="kw">=</span> <span class="fl">30</span>, <span class="kw">r</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">sd</span> <span class="kw">=</span> <span class="fl">10</span>, <span class="kw">dv</span> <span class="kw">=</span> <span class="st">"size"</span>,
               <span class="kw">long</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">plot</span> <span class="kw">=</span> <span class="fl">TRUE</span>
  )</pre></body></html></div>
<p><img src="export_files/figure-html/unnamed-chunk-2-1.png" width="700"></p>
<pre><code>#&gt; id set to type string
#&gt; group set to type string
#&gt; time set to type string
#&gt; size set to type float</code></pre>
<p><img src="export_files/figure-html/unnamed-chunk-2-2.png" width="700"></p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="no">s</span> <span class="kw">&lt;-</span> <span class="no">s</span> <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_hypothesis.html">add_hypothesis</a></span>(<span class="st">"group"</span>, <span class="st">"Group A will be bigger than group B"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_analysis.html">add_analysis</a></span>(<span class="st">"A1"</span>, <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span>(<span class="no">size</span>~<span class="no">group</span>, <span class="no">dat</span>)) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_criterion.html">add_criterion</a></span>(<span class="st">"p"</span>, <span class="st">"p.value"</span>, <span class="st">"&lt;"</span>, <span class="fl">0.05</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_criterion.html">add_criterion</a></span>(<span class="st">"dir"</span>, <span class="st">"estimate[1]"</span>, <span class="st">"&gt;"</span>, <span class="st">"estimate[2]"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_eval.html">add_eval</a></span>(<span class="st">"c"</span>, <span class="st">"significant in predicted direction"</span>, <span class="st">"p &amp; dir"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_eval.html">add_eval</a></span>(<span class="st">"f"</span>, <span class="st">"significant in unpredicted direction"</span>, <span class="st">"p &amp; !dir"</span>) <span class="kw">%&gt;%</span>

  <span class="fu"><a href="../reference/add_hypothesis.html">add_hypothesis</a></span>(<span class="st">"time"</span>, <span class="st">"Subjects will be bigger in the morning than at night"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_analysis.html">add_analysis</a></span>(<span class="st">"A2"</span>, <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span>(<span class="no">size</span>~<span class="no">time</span>, <span class="no">dat</span>)) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_criterion.html">add_criterion</a></span>(<span class="st">"p"</span>, <span class="st">"p.value"</span>, <span class="st">"&lt;"</span>, <span class="fl">0.05</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_criterion.html">add_criterion</a></span>(<span class="st">"dir"</span>, <span class="st">"estimate[1]"</span>, <span class="st">"&gt;"</span>, <span class="st">"estimate[2]"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_eval.html">add_eval</a></span>(<span class="st">"c"</span>, <span class="st">"significant in predicted direction"</span>, <span class="st">"p &amp; dir"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/add_eval.html">add_eval</a></span>(<span class="st">"f"</span>, <span class="st">"significant in unpredicted direction"</span>, <span class="st">"p &amp; !dir"</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="../reference/study_analyse.html">study_analyse</a></span>()
<span class="co">#&gt; Hypothesis `group`, Criterion `p`:</span>
<span class="co">#&gt;     p.value &lt; 0.05 is FALSE</span>
<span class="co">#&gt;     p.value = 0.81</span>
<span class="co">#&gt; Hypothesis `group`, Criterion `dir`:</span>
<span class="co">#&gt;     estimate[1] &gt; estimate[2] is FALSE</span>
<span class="co">#&gt;     estimate[1] = 101.10</span>
<span class="co">#&gt;     estimate[2] = 101.5532282802</span>
<span class="co">#&gt; Hypothesis group:</span>
<span class="co">#&gt;     Corroborate: FALSE</span>
<span class="co">#&gt;     Falsify: FALSE</span>
<span class="co">#&gt;     Conclusion: inconclusive</span>
<span class="co">#&gt; Hypothesis `time`, Criterion `p`:</span>
<span class="co">#&gt;     p.value &lt; 0.05 is TRUE</span>
<span class="co">#&gt;     p.value = 0.02</span>
<span class="co">#&gt; Hypothesis `time`, Criterion `dir`:</span>
<span class="co">#&gt;     estimate[1] &gt; estimate[2] is TRUE</span>
<span class="co">#&gt;     estimate[1] = 103.42</span>
<span class="co">#&gt;     estimate[2] = 99.2390252648151</span>
<span class="co">#&gt; Hypothesis time:</span>
<span class="co">#&gt;     Corroborate: TRUE</span>
<span class="co">#&gt;     Falsify: FALSE</span>
<span class="co">#&gt;     Conclusion: corroborate</span></pre></body></html></div>
<p>You can save the study in JSON (machine-readable) format and reload it later.</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="fu"><a href="../reference/study_save.html">study_save</a></span>(<span class="no">s</span>, <span class="st">"study.json"</span>)
<span class="co">#&gt; Saving to /Users/lisad/rproj/scienceverse/scienceverse/vignettes/study.json</span>

<span class="no">s</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/study.html">study</a></span>(<span class="st">"study.json"</span>)
<span class="co">#&gt; Loaded custom function: analysis_A1</span>
<span class="co">#&gt; Loaded custom function: analysis_A2</span></pre></body></html></div>
<p>You can get all the results with the <code><a href="../reference/get_result.html">get_result()</a></code> function. If you don’t specify the result name or the analysis ID, it defaults to all of the results of the first analysis. It retruns a list that you can use, but will display an RMarkdown-formatted list if you print it (and set the chunk options to <code>results='asis'</code>).</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="../reference/get_result.html">get_result</a></span>(<span class="no">s</span>)</pre></body></html></div>
<ul>
<li>statistic: -0.2403</li>
<li>parameter: 111.5102</li>
<li>p.value: 0.8106</li>
<li>conf.int:
<ul>
<li>-4.1552</li>
<li>3.2564</li>
</ul>
</li>
<li>estimate:
<ul>
<li>101.1039</li>
<li>101.5532</li>
</ul>
</li>
<li>null.value: 0</li>
<li>stderr: 1.8702</li>
<li>alternative: two.sided</li>
<li>method: Welch Two Sample t-test</li>
<li>data.name: size by group</li>
</ul>
<p>Get a specific result from a specific analysis.</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="fu"><a href="../reference/get_result.html">get_result</a></span>(<span class="kw">study</span> <span class="kw">=</span> <span class="no">s</span>,
           <span class="kw">result</span> <span class="kw">=</span> <span class="st">"p.value"</span>,
           <span class="kw">analysis_id</span> <span class="kw">=</span> <span class="st">"A2"</span>,
           <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">3</span>,
           <span class="kw">return</span> <span class="kw">=</span> <span class="st">"value"</span>)
<span class="co">#&gt; [1] 0.024</span></pre></body></html></div>
<p>Set <code>value</code> to <code>char</code> if you want to keep trailing zeros (return the number as a character string).</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="../reference/get_result.html">get_result</a></span>(<span class="kw">study</span> <span class="kw">=</span> <span class="no">s</span>,
           <span class="kw">result</span> <span class="kw">=</span> <span class="st">"parameter"</span>,
           <span class="kw">analysis_id</span> <span class="kw">=</span> <span class="fl">1</span>,
           <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">3</span>,
           <span class="kw">return</span> <span class="kw">=</span> <span class="st">"char"</span>)
<span class="co">#&gt; [1] "111.510"</span></pre></body></html></div>
<p>You can display the value as a link to the analysis file (created with <code>make_script</code>). The digits default to the global option, so you can reset that. And you can use the shorthand function <code>get_html</code> if you only have one study object loaded. The analysis link defaults to “analysis.html”, but you can change this with <code><a href="../reference/scienceverse_options.html">scienceverse_options()</a></code> as shown.</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="fu"><a href="../reference/make_script.html">make_script</a></span>(<span class="no">s</span>, <span class="st">"analysis.Rmd"</span>)
<span class="kw pkg">rmarkdown</span><span class="kw ns">::</span><span class="fu"><a href="https://rdrr.io/pkg/rmarkdown/man/render.html">render</a></span>(<span class="st">"analysis.Rmd"</span>)
<span class="co">#&gt; /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS analysis.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output analysis.html --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 --variable toc_smooth_scroll=1 --variable toc_print=1 --template /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/6w/y3tyzgs1403cz7tgw8k4lk600000gq/T//Rtmp7Eqcaw/rmarkdown-str59812a16aa6.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/latex-div.lua</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span>(<span class="kw">digits</span> <span class="kw">=</span> <span class="fl">3</span>)
<span class="fu"><a href="../reference/scienceverse_options.html">scienceverse_options</a></span>(<span class="kw">analysis_link</span> <span class="kw">=</span> <span class="st">"analysis.html"</span>)
<span class="fu"><a href="../reference/get_html.html">get_html</a></span>(<span class="st">"p.value"</span>)
<span class="co">#&gt; [1] "&lt;a href='analysis.html#analysis_1' title='Analysis 1 Result p.value'&gt;0.811&lt;/a&gt;"</span></pre></body></html></div>
<p>You’ll probably want to use <code><a href="../reference/get_html.html">get_html()</a></code> inline most of the time like this:</p>
<p>For hypothesis 1, the subjects in group A were not any bigger than those in group B (t = <a href="analysis.html#analysis_1" title="Analysis 1 Result statistic">-0.24</a>, df = <a href="analysis.html#analysis_1" title="Analysis 1 Result parameter">111.5</a>, p = <a href="analysis.html#analysis_1" title="Analysis 1 Result p.value">0.811</a>, 95% CI = [<a href="analysis.html#analysis_1" title="Analysis 1 Result conf.int[1]">-4.16</a>, <a href="analysis.html#analysis_1" title="Analysis 1 Result conf.int[2]">3.26</a>]).</p>
<p>For hypothesis 1, the subjects were larger in the morning than at night (t = <a href="analysis.html#analysis_2" title="Analysis 2 Result statistic">2.28</a>, df = <a href="analysis.html#analysis_2" title="Analysis 2 Result parameter">116.1</a>, p = <a href="analysis.html#analysis_2" title="Analysis 2 Result p.value">0.024</a>, 95% CI = [<a href="analysis.html#analysis_2" title="Analysis 2 Result conf.int[1]">0.55</a>, <a href="analysis.html#analysis_2" title="Analysis 2 Result conf.int[2]">7.80</a>]).</p>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Lisa DeBruine, Daniel Lakens.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
